services:
  - type: web
    name: gutensight-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    nodeVersion: 18.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=1536
